import React, { createContext, useContext, ReactNode } from "react";
import { Language } from "../types";

// Bilingual Translations
export const translations = {
  zh: {
    appName: "Go Travel",
    yourTrips: "您的旅程",
    newTrip: "新增旅程",
    overview: "概覽",
    itinerary: "行程",
    checklist: "清單",
    expenses: "花費",
    tickets: "機票",
    syncing: "同步中...",
    countdown: "倒數",
    packingProgress: "行李準備",
    budgetStatus: "預算控制",
    daysLeft: "天",
    permissionEditor: "擁有者",
    permissionGuest: "協作者",
    upcoming: "即將到來",
    noUpcoming: "尚無行程",
    deleteTrip: "刪除旅程",
    confirmDelete: "確定刪除此旅程？此動作無法復原。",
    heroTitle: "聰明規劃，\n自在旅行。",
    heroSubtitle: "全方位的旅程規劃空間。",
    login: "登入 / 開始",
    errorTitle: "同步錯誤",
    errorDesc: "無法載入資料",
    setupRequired: "請設定機票",
    upcomingSchedule: "即將到來的行程",
    viewMap: "地圖",
    editBudget: "編輯預算",
    totalCost: "旅程總花費",
    includesFlight: "包含機票",
    breakdown: "類別佔比",
    addEntry: "新增支出",
    filterAll: "全部",
    filterUser: "成員",
    noExpenses: "尚無支出記錄",
    descRequired: "請輸入備註",
    amountRequired: "請輸入金額",
    confirmDeleteItems: "確定刪除嗎？",
    FlightTickets: "機票",
    save: "確認",
    cancel: "取消",
    amount: "金額",
    addPlace: "新增景點",
    addFood: "新增餐廳",
    editActivity: "編輯行程",
    newActivity: "新增行程",
    addChecklistItem: "新增項目",
    placeName: "地點名稱",
    time: "時間",
    note: "備註",
    noData: "暫無資料",
    selectTransport: "選擇交通方式",
    moving: "移動",
    readOnly: "僅供檢視",
    type: "類型",
    typePlace: "景點",
    typeFood: "餐飲",
    transportPublic: "大眾運輸",
    transportCar: "汽車",
    transportBike: "腳踏車",
    transportWalk: "步行",
    transportFlight: "飛機",
    catFood: "餐飲",
    catAccom: "住宿",
    catTransport: "交通",
    catTickets: "票券",
    catShopping: "購物",
    catOther: "其他",
    catDocs: "證件",
    catGear: "電器",
    catCloth: "衣物",
    catToilet: "盥洗",
    catFlight: "機票",
    searchOut: "搜尋去程",
    searchIn: "搜尋回程",
    selectOut: "選擇去程",
    selectIn: "選擇回程",
    origin: "出發地",
    destination: "目的地",
    date: "日期",
    flightNo: "航班代號",
    search: "搜尋",
    review: "確認行程",
    back: "返回",
    confirm: "確認",
    traveler: "旅客姓名",
    cabin: "艙等",
    totalPrice: "總票價",
    baggage: "行李",
    outboundBag: "去程行李",
    inboundBag: "回程行李",
    priceRequired: "請輸入金額",
    carryOn: "手提",
    checked: "託運",
    count: "件",
    weight: "Kg",
    airline: "航空公司",
    terminal: "航廈",
    flight: "航班",
    dep: "起飛",
    arr: "抵達",
    boardingTime: "登機時間",
    titleFlights: "成員航班",
    addMyFlight: "新增我的機票",
    addSegment: "新增航段",
    edit: "編輯",
    required: "必填",
    weightRequired: "請輸入重量",
    noFlights: "尚無機票",
    checklistSummary: "清單概況",
    completed: "已完成",
    tripNotFound: "找不到旅程或無權限存取",
    backHome: "返回首頁",
    shareTrip: "分享旅程",
    inviteEmail: "邀請 Email",
    invite: "邀請",
    collaborators: "協作者",
    shareLink: "分享連結",
    copied: "已複製",
    copy: "複製",
    emailPlaceholder: "輸入 Email",
    owner: "擁有者",
    accessDenied: "存取被拒",
    askOwner: "請將此 Email 提供給擁有者以獲取權限：",
    join: "加入旅程",
    revoked: "您的權限已被移除",
    spent: "已支出",
    limit: "預算",
    syncWithOwner: "與建立者相同航班",
    outbound: "去程",
    inbound: "回程",
    you: "您",
    youOwner: "您 (建立者)",
    creator: "建立者",
    nextActivity: "下一站",
    nextStops: "下五站 stops",
    statusJoined: "已加入",
    statusPending: "等待中",
  },
  en: {
    appName: "Go Travel",
    yourTrips: "Your Trips",
    newTrip: "New Trip",
    overview: "Overview",
    itinerary: "Itinerary",
    checklist: "Checklist",
    expenses: "Expenses",
    tickets: "Tickets",
    syncing: "Syncing...",
    countdown: "Countdown",
    packingProgress: "Packing",
    budgetStatus: "Budget",
    daysLeft: "Days",
    permissionEditor: "Owner",
    permissionGuest: "Guest",
    upcoming: "Upcoming",
    noUpcoming: "No Items",
    deleteTrip: "Delete Trip",
    confirmDelete: "Delete trip? Irreversible.",
    heroTitle: "Travel Smart.",
    heroSubtitle: "All-in-one workspace.",
    login: "Login / Start",
    errorTitle: "Sync Error",
    errorDesc: "Failed to load",
    setupRequired: "Setup Flight",
    upcomingSchedule: "Upcoming Schedule",
    viewMap: "Map",
    editBudget: "Edit Budget",
    totalCost: "Total Cost",
    includesFlight: "Inc. Flights",
    breakdown: "Breakdown",
    addEntry: "Add Expense",
    filterAll: "All",
    filterUser: "Member",
    noExpenses: "No Data",
    descRequired: "Note Required",
    amountRequired: "Amount Required",
    confirmDeleteItems: "Delete?",
    FlightTickets: "Flights",
    save: "Save",
    cancel: "Cancel",
    amount: "Amount",
    addPlace: "Add Place",
    addFood: "Add Food",
    editActivity: "Edit Item",
    newActivity: "New Item",
    addChecklistItem: "Add Item",
    placeName: "Place Name",
    time: "Time",
    note: "Notes",
    noData: "No Data",
    selectTransport: "Transport",
    moving: "Move",
    readOnly: "Read Only",
    type: "Type",
    typePlace: "Place",
    typeFood: "Food",
    transportPublic: "Public",
    transportCar: "Car",
    transportBike: "Bike",
    transportWalk: "Walk",
    transportFlight: "Flight",
    catFood: "Food",
    catAccom: "Stay",
    catTransport: "Transport",
    catTickets: "Tickets",
    catShopping: "Shopping",
    catOther: "Other",
    catDocs: "Documents",
    catGear: "Electronics",
    catCloth: "Clothing",
    catToilet: "Toiletries",
    catFlight: "Flights",
    searchOut: "Outbound Search",
    searchIn: "Inbound Search",
    selectOut: "Select Outbound",
    selectIn: "Select Inbound",
    origin: "Origin",
    destination: "Destination",
    date: "Date",
    flightNo: "Flight No.",
    search: "Search",
    review: "Review",
    back: "Back",
    confirm: "Confirm",
    traveler: "Traveler",
    cabin: "Cabin",
    totalPrice: "Total Price",
    baggage: "Baggage",
    outboundBag: "Outbound Baggage",
    inboundBag: "Inbound Baggage",
    priceRequired: "Price Required",
    carryOn: "Carry-On",
    checked: "Checked",
    count: "Pcs",
    weight: "Kg",
    airline: "Airline",
    terminal: "Terminal",
    flight: "Flight",
    dep: "Dep",
    arr: "Arr",
    boardingTime: "Boarding",
    titleFlights: "Flights",
    addMyFlight: "Add Mine",
    addSegment: "Add Segment",
    edit: "Edit",
    required: "Required",
    weightRequired: "Weight Required",
    noFlights: "No Flights",
    checklistSummary: "Packing Status",
    completed: "Done",
    tripNotFound: "Trip not found or access denied",
    backHome: "Back to Home",
    shareTrip: "Share Trip",
    inviteEmail: "Invite Email",
    invite: "Invite",
    collaborators: "Collaborators",
    shareLink: "Share Link",
    copied: "Copied",
    copy: "Copy",
    emailPlaceholder: "Enter Email",
    owner: "Owner",
    accessDenied: "Access Denied",
    askOwner: "Please give this email to the owner to get access:",
    join: "Join Trip",
    revoked: "Access Revoked",
    spent: "Spent",
    limit: "Limit",
    syncWithOwner: "Sync with Owner",
    outbound: "Outbound",
    inbound: "Inbound",
    you: "You",
    youOwner: "You (Creator)",
    creator: "Creator",
    nextActivity: "Next Activity",
    nextStops: "Next 5 stops",
    statusJoined: "Joined",
    statusPending: "Pending",
  },
};

type LocalizationContextType = {
  t: (key: keyof typeof translations.en) => string;
  language: Language;
  setLanguage: (lang: Language) => void;
};

const LocalizationContext = createContext<LocalizationContextType | undefined>(
  undefined
);

export const LocalizationProvider: React.FC<{
  children: ReactNode;
  value: LocalizationContextType;
}> = ({ children, value }) => {
  return (
    <LocalizationContext.Provider value={value}>
      {children}
    </LocalizationContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LocalizationContext);
  if (!context)
    throw new Error(
      "useTranslation must be used within a LocalizationProvider"
    );
  return context;
};
