import React, { createContext, useContext, ReactNode } from "react";
import { Language } from "../types";

// Bilingual Translations
export const translations = {
  zh: {
    appName: "Go Travel",
    yourTrips: "您的旅程",
    newTrip: "新增旅程",
    overview: "概覽",
    itinerary: "行程",
    checklist: "清單",
    expenses: "花費",
    tickets: "機票",
    syncing: "同步中...",
    countdown: "倒數",
    packingProgress: "行李準備",
    budgetStatus: "預算控制",
    daysLeft: "天",
    permissionEditor: "擁有者",
    permissionGuest: "協作者",
    upcoming: "即將到來",
    noUpcoming: "尚無行程",
    deleteTrip: "刪除旅程",
    confirmDelete: "確定刪除此旅程？此動作無法復原。",
    heroTitle: "聰明規劃，\n自在旅行。",
    heroSubtitle: "全方位的旅程規劃空間。",
    login: "登入 / 開始",
    loggingIn: "登入中...",
    logoutSuccess: "已安全登出",
    loginFailed: "登入失敗，請稍後再試",
    configMissing: "尚未設定 Supabase 連線資訊 (請檢查環境變數)",
    guestPreview: "訪客預覽",
    guestBannerText: "您目前正在以唯讀模式預覽此旅程。",
    loginToJoin: "登入以共同編輯",
    emailLogin: "Email 免密碼登入",
    enterEmail: "輸入您的 Email",
    sendMagicLink: "發送登入連結",
    sendingMagicLink: "發送中...",
    magicLinkSent: "登入連結已寄送！請至信箱收信並點擊連結登入。",
    invalidEmail: "請輸入有效的 Email 地址",
    orDivider: "或",
    googleLogin: "使用 Google 帳號快速登入",
    loginModalTitle: "登入 Go Travel",
    loginModalSubtitle: "登入即可與旅伴即時共同編輯、記帳與規劃行程",
    previewModeNotice: "訪客模式下無法進行編輯，請登入以解鎖完整功能。",
    errorTitle: "同步錯誤",
    errorDesc: "無法載入資料",
    setupRequired: "請設定機票",
    upcomingSchedule: "即將到來的行程",
    viewMap: "地圖",
    editBudget: "編輯預算",
    totalCost: "旅程總花費",
    includesFlight: "包含機票",
    breakdown: "類別佔比",
    addEntry: "新增支出",
    filterAll: "全部",
    filterUser: "成員",
    filterDate: "日期",
    filterAllDates: "所有日期",
    sortDateDesc: "時間 (最近)",
    sortDateAsc: "時間 (最遠)",
    sortCreatedDesc: "新增時間 (最近)",
    sortAmountDesc: "金額 (高到低)",
    sortAmountAsc: "金額 (低到高)",
    noExpenses: "尚無支出記錄",
    descRequired: "請輸入備註",
    amountRequired: "請輸入金額",
    confirmDeleteItems: "確定刪除嗎？",
    FlightTickets: "機票",
    save: "確認",
    cancel: "取消",
    amount: "金額",
    addPlace: "新增景點",
    addFood: "新增餐廳",
    editActivity: "編輯行程",
    newActivity: "新增行程",
    addChecklistItem: "新增項目",
    placeName: "地點名稱",
    time: "時間",
    note: "備註",
    noData: "暫無資料",
    selectTransport: "選擇交通方式",
    moving: "移動",
    readOnly: "僅供檢視",
    type: "類型",
    typePlace: "景點",
    typeFood: "餐飲",
    transportPublic: "大眾運輸",
    transportCar: "汽車",
    transportBike: "腳踏車",
    transportWalk: "步行",
    transportFlight: "飛機",
    catFood: "餐飲",
    catAccom: "住宿",
    catTransport: "交通",
    catTickets: "票券",
    catShopping: "購物",
    catOther: "其他",
    catDocs: "證件",
    catGear: "電器",
    catCloth: "衣物",
    catToilet: "盥洗",
    catFlight: "機票",
    searchOut: "搜尋去程",
    searchIn: "搜尋回程",
    selectOut: "選擇去程",
    selectIn: "選擇回程",
    origin: "出發地",
    destination: "目的地",
    date: "日期",
    flightNo: "航班代號",
    search: "搜尋",
    review: "確認行程",
    back: "返回",
    confirm: "確認",
    traveler: "旅客姓名",
    cabin: "艙等",
    totalPrice: "總票價",
    baggage: "行李",
    outboundBag: "去程行李",
    inboundBag: "回程行李",
    priceRequired: "請輸入金額",
    carryOn: "手提",
    checked: "託運",
    count: "件",
    weight: "Kg",
    airline: "航空公司",
    terminal: "航廈",
    flight: "航班",
    dep: "起飛",
    arr: "抵達",
    boardingTime: "登機時間",
    titleFlights: "成員航班",
    addMyFlight: "新增我的機票",
    addSegment: "新增航段",
    edit: "編輯",
    required: "必填",
    weightRequired: "請輸入重量",
    noFlights: "尚無機票",
    checklistSummary: "清單概況",
    completed: "已完成",
    tripNotFound: "找不到旅程或無權限存取",
    backHome: "返回首頁",
    shareTrip: "分享旅程",
    inviteEmail: "邀請 Email",
    invite: "邀請",
    collaborators: "協作者",
    shareLink: "分享連結",
    copied: "已複製",
    copy: "複製",
    emailPlaceholder: "輸入 Email",
    owner: "擁有者",
    accessDenied: "存取被拒",
    askOwner: "請將此 Email 提供給擁有者以獲取權限：",
    join: "加入旅程",
    revoked: "您的權限已被移除",
    spent: "已支出",
    limit: "預算",
    syncWithOwner: "與建立者相同航班",
    outbound: "去程",
    inbound: "回程",
    you: "您",
    youOwner: "您 (建立者)",
    creator: "建立者",
    nextActivity: "下一站",
    nextStops: "下五站 stops",
    statusJoined: "已加入",
    statusPending: "等待中",
    layoverAt: "轉機於",
    addLayoverSegment: "新增轉機航段",
    nextToInbound: "下一步：搜尋回程",
    nextToReview: "下一步：確認行程",
    outboundSelected: "已選擇去程航班",
    inboundSelected: "已選擇回程航班",
    editFlightDetails: "手動修改航班時間與資訊",
    gate: "登機門",
    departureAirport: "出發機場",
    arrivalAirport: "抵達機場",
    departureTime: "出發時間",
    arrivalTime: "抵達時間",
    show: "顯示",
    hide: "隱藏",
    segmentLeg: "航段",
    tripNotFoundDesc: "請確認分享連結是否正確，或是您是否有權限存取此行程。",
    sessionExpired: "登入已過期或需要登入，請登入以檢視該行程",
    loginToViewTrip: "此行程需要登入存取，登入後將自動為您開啟",
    sessionExpiredTitle: "登入階段已逾時",
    sessionExpiredDesc: "您的登入已過期。為保護行程安全，請重新登入，系統已為您暫存目標行程！",
    loginRequiredTitle: "需要登入以存取行程",
    loginRequiredDesc: "您欲查看的行程需要登入權限。登入後將自動開啟此行程！",
    targetTripSaved: "目標行程已暫存，登入後立即開啟",
    reloginAndContinue: "重新登入並返回行程",
    loginAndContinue: "登入並開啟行程",
    exploreLanding: "暫時留在首頁",
    tripNotFoundRedirect: "找不到此行程或無權限存取，已為您跳轉至您的行程頁面",
    loginRequiredRedirect: "此行程需要登入存取，已為您前往登入主頁",
    noPermissionRedirect: "您沒有此行程的存取權限，已為您跳轉至您的行程頁面",
    deleteTripConfirmTitle: "刪除此旅程",
    deleteTripConfirmDesc: "確定要刪除「{name}」嗎？此動作將會永久刪除所有行程、清單、記帳與機票資料，且無法復原。",
    leaveTripConfirmTitle: "退出此旅程",
    leaveTripConfirmDesc: "確定要退出「{name}」嗎？退出後您將不再具有此旅程的存取權限。",
    leaveTrip: "退出旅程",
    tripDeletedSuccess: "已成功刪除旅程",
    tripLeaveSuccess: "已成功退出旅程",
    deleteFailed: "刪除旅程失敗，請稍後再試",
    leaveFailed: "退出旅程失敗，請稍後再試",
    filterUpcoming: "即將出發",
    filterOngoing: "進行中",
    filterPast: "已結束",
    searchTripsPlaceholder: "搜尋旅程名稱或目的地...",
    noTripsFound: "找不到符合條件的旅程",
    noTripsFoundDesc: "嘗試更換搜尋關鍵字或切換篩選分類",
    clearFilter: "清除搜尋與篩選",
    emptyTripsTitle: "開啟你的第一趟冒險",
    emptyTripsDesc: "規劃行程、管理機票與預算，並即時邀請旅伴共同編輯。",
    createFirstTrip: "建立第一個旅程",
    daysCount: "天",
    placesCount: "個景點",
    buddiesCount: "位旅伴",
    statusOngoing: "進行中",
    statusUpcomingIn: "天後出發",
    statusPast: "已結束",
    statusToday: "今天出發",
    deleting: "處理中...",
    actionIrreversible: "永久刪除無法復原",
    done: "完成",
    manage: "管理",
    manageTripsHint: "點擊卡片右上角圖示刪除或退出旅程",
  },
  en: {
    appName: "Go Travel",
    yourTrips: "Your Trips",
    newTrip: "New Trip",
    overview: "Overview",
    itinerary: "Itinerary",
    checklist: "Checklist",
    expenses: "Expenses",
    tickets: "Tickets",
    syncing: "Syncing...",
    countdown: "Countdown",
    packingProgress: "Packing",
    budgetStatus: "Budget",
    daysLeft: "Days",
    permissionEditor: "Owner",
    permissionGuest: "Guest",
    upcoming: "Upcoming",
    noUpcoming: "No Items",
    deleteTrip: "Delete Trip",
    confirmDelete: "Delete trip? Irreversible.",
    heroTitle: "Travel Smart.",
    heroSubtitle: "All-in-one workspace.",
    login: "Login / Start",
    loggingIn: "Signing in...",
    logoutSuccess: "Signed out successfully",
    loginFailed: "Sign in failed, please try again",
    configMissing: "Supabase configuration is missing (check env vars)",
    guestPreview: "Guest Preview",
    guestBannerText: "You are previewing this trip in read-only mode.",
    loginToJoin: "Log in to collaborate",
    emailLogin: "Email Magic Link",
    enterEmail: "Enter your email",
    sendMagicLink: "Send Login Link",
    sendingMagicLink: "Sending...",
    magicLinkSent: "Login link sent! Please check your email to complete sign in.",
    invalidEmail: "Please enter a valid email address",
    orDivider: "or",
    googleLogin: "Continue with Google",
    loginModalTitle: "Sign in to Go Travel",
    loginModalSubtitle: "Sign in to collaborate, track expenses, and plan with travel buddies",
    previewModeNotice: "Editing is disabled in guest mode. Please sign in to unlock all features.",
    errorTitle: "Sync Error",
    errorDesc: "Failed to load",
    setupRequired: "Setup Flight",
    upcomingSchedule: "Upcoming Schedule",
    viewMap: "Map",
    editBudget: "Edit Budget",
    totalCost: "Total Cost",
    includesFlight: "Inc. Flights",
    breakdown: "Breakdown",
    addEntry: "Add Expense",
    filterAll: "All",
    filterUser: "Member",
    filterDate: "Date",
    filterAllDates: "All Dates",
    sortDateDesc: "Time (Newest)",
    sortDateAsc: "Time (Oldest)",
    sortCreatedDesc: "Added (Newest)",
    sortAmountDesc: "Amount (High-Low)",
    sortAmountAsc: "Amount (Low-High)",
    noExpenses: "No Data",
    descRequired: "Note Required",
    amountRequired: "Amount Required",
    confirmDeleteItems: "Delete?",
    FlightTickets: "Flights",
    save: "Save",
    cancel: "Cancel",
    amount: "Amount",
    addPlace: "Add Place",
    addFood: "Add Food",
    editActivity: "Edit Item",
    newActivity: "New Item",
    addChecklistItem: "Add Item",
    placeName: "Place Name",
    time: "Time",
    note: "Notes",
    noData: "No Data",
    selectTransport: "Transport",
    moving: "Move",
    readOnly: "Read Only",
    type: "Type",
    typePlace: "Place",
    typeFood: "Food",
    transportPublic: "Public",
    transportCar: "Car",
    transportBike: "Bike",
    transportWalk: "Walk",
    transportFlight: "Flight",
    catFood: "Food",
    catAccom: "Stay",
    catTransport: "Transport",
    catTickets: "Tickets",
    catShopping: "Shopping",
    catOther: "Other",
    catDocs: "Documents",
    catGear: "Electronics",
    catCloth: "Clothing",
    catToilet: "Toiletries",
    catFlight: "Flights",
    searchOut: "Outbound Search",
    searchIn: "Inbound Search",
    selectOut: "Select Outbound",
    selectIn: "Select Inbound",
    origin: "Origin",
    destination: "Destination",
    date: "Date",
    flightNo: "Flight No.",
    search: "Search",
    review: "Review",
    back: "Back",
    confirm: "Confirm",
    traveler: "Traveler",
    cabin: "Cabin",
    totalPrice: "Total Price",
    baggage: "Baggage",
    outboundBag: "Outbound Baggage",
    inboundBag: "Inbound Baggage",
    priceRequired: "Price Required",
    carryOn: "Carry-On",
    checked: "Checked",
    count: "Pcs",
    weight: "Kg",
    airline: "Airline",
    terminal: "Terminal",
    flight: "Flight",
    dep: "Dep",
    arr: "Arr",
    boardingTime: "Boarding",
    titleFlights: "Flights",
    addMyFlight: "Add Mine",
    addSegment: "Add Segment",
    edit: "Edit",
    required: "Required",
    weightRequired: "Weight Required",
    noFlights: "No Flights",
    checklistSummary: "Packing Status",
    completed: "Done",
    tripNotFound: "Trip not found or access denied",
    backHome: "Back to Home",
    shareTrip: "Share Trip",
    inviteEmail: "Invite Email",
    invite: "Invite",
    collaborators: "Collaborators",
    shareLink: "Share Link",
    copied: "Copied",
    copy: "Copy",
    emailPlaceholder: "Enter Email",
    owner: "Owner",
    accessDenied: "Access Denied",
    askOwner: "Please give this email to the owner to get access:",
    join: "Join Trip",
    revoked: "Access Revoked",
    spent: "Spent",
    limit: "Limit",
    syncWithOwner: "Sync with Owner",
    outbound: "Outbound",
    inbound: "Inbound",
    you: "You",
    youOwner: "You (Creator)",
    creator: "Creator",
    nextActivity: "Next Activity",
    nextStops: "Next 5 stops",
    statusJoined: "Joined",
    statusPending: "Pending",
    layoverAt: "Layover at",
    addLayoverSegment: "Add Layover Leg",
    nextToInbound: "Next: Search Inbound",
    nextToReview: "Next: Review",
    outboundSelected: "Selected Outbound Flights",
    inboundSelected: "Selected Inbound Flights",
    editFlightDetails: "Edit Flight Details & Times",
    gate: "Gate",
    departureAirport: "Departure Airport",
    arrivalAirport: "Arrival Airport",
    departureTime: "Departure Time",
    arrivalTime: "Arrival Time",
    show: "Show",
    hide: "Hide",
    segmentLeg: "Leg",
    tripNotFoundDesc: "Please check if the share link is valid or if you have permission to view it.",
    sessionExpired: "Session expired or login required. Please sign in to view this trip.",
    loginToViewTrip: "This trip requires login. You will be automatically redirected after sign-in.",
    sessionExpiredTitle: "Session Expired",
    sessionExpiredDesc: "Your login session has expired. Please sign in again; your destination trip is preserved!",
    loginRequiredTitle: "Sign In Required",
    loginRequiredDesc: "This trip requires authentication. You will be redirected right into it after signing in!",
    targetTripSaved: "Destination trip saved, you will be redirected after login",
    reloginAndContinue: "Sign in and continue to trip",
    loginAndContinue: "Sign in and open trip",
    exploreLanding: "Browse homepage first",
    tripNotFoundRedirect: "Trip not found or no permission, redirected to your trips.",
    loginRequiredRedirect: "Login required to view this trip, redirected to login page.",
    noPermissionRedirect: "You do not have permission to view this trip, redirected to your trips.",
    deleteTripConfirmTitle: "Delete Trip",
    deleteTripConfirmDesc: "Are you sure you want to delete \"{name}\"? This will permanently remove all itinerary, checklist, expense, and flight records. This action cannot be undone.",
    leaveTripConfirmTitle: "Leave Trip",
    leaveTripConfirmDesc: "Are you sure you want to leave \"{name}\"? You will no longer have access to this trip.",
    leaveTrip: "Leave Trip",
    tripDeletedSuccess: "Trip deleted successfully",
    tripLeaveSuccess: "Left trip successfully",
    deleteFailed: "Failed to delete trip, please try again",
    leaveFailed: "Failed to leave trip, please try again",
    filterUpcoming: "Upcoming",
    filterOngoing: "Ongoing",
    filterPast: "Past",
    searchTripsPlaceholder: "Search by trip name or destination...",
    noTripsFound: "No matching trips found",
    noTripsFoundDesc: "Try adjusting your search keywords or switching filters",
    clearFilter: "Clear search & filters",
    emptyTripsTitle: "Start Your First Adventure",
    emptyTripsDesc: "Plan itineraries, manage flights and budgets, and invite travel buddies to collaborate in real-time.",
    createFirstTrip: "Create First Trip",
    daysCount: "days",
    placesCount: "places",
    buddiesCount: "buddies",
    statusOngoing: "Ongoing",
    statusUpcomingIn: "days to go",
    statusPast: "Past",
    statusToday: "Starts today",
    deleting: "Deleting...",
    actionIrreversible: "Irreversible action",
    done: "Done",
    manage: "Manage",
    manageTripsHint: "Tap the badge on any card to delete or leave",
  },
};

type LocalizationContextType = {
  t: (key: keyof typeof translations.en) => string;
  language: Language;
  setLanguage: (lang: Language) => void;
};

const LocalizationContext = createContext<LocalizationContextType | undefined>(
  undefined
);

export const LocalizationProvider: React.FC<{
  children: ReactNode;
  value?: LocalizationContextType;
}> = ({ children, value }) => {
  const defaultValue: LocalizationContextType = {
    t: (key: keyof typeof translations.en) =>
      (translations.zh as any)[key] || (translations.en as any)[key] || key,
    language: "zh",
    setLanguage: () => {},
  };
  return (
    <LocalizationContext.Provider value={value || defaultValue}>
      {children}
    </LocalizationContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LocalizationContext);
  if (!context)
    throw new Error(
      "useTranslation must be used within a LocalizationProvider"
    );
  return context;
};
